### ISSUE TITLE
Add Env Vars

### ISSUE THREAD

**Issue by wilsonodk** [turnerlabs/customs-api#31]
Allow Env Vars to be sent when using the deploy endpoint.

```yaml
envVars
- type:        Array
- required:    false
- description: An array of Env Vars to be put onto the Container of the Shipment
- requirement: An array
```

The Shipment's current Container Env Vars will be checked against this list one by one with the following results:

+ If the name of an incoming Env Var is not found; add the Env Var.

+ If the name of an incoming Env Var matches an existing Env Var; update the value of the existing Env Var (so long as the value is not an empty string).

+ If the name of an incoming Env Var matches an existing Env Var AND the value of the incoming Env Var is `""` (empty string); delete the Env Var.

+ All existing Env Vars that do not match an incoming Env Var will be left alone.
